table Customer
	lineageTag: 1fc7c150-0b2d-4430-93a9-83b29bb9bbfd

	column 'Customer name'
		dataType: string
		lineageTag: 02ae6f45-dff4-4045-afca-d989cf597135
		summarizeBy: none
		sourceColumn: Customer name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Customer Contact'
		dataType: int64
		formatString: 0
		lineageTag: ca80b1f4-04d7-4ad5-8979-60ec9dc6b399
		summarizeBy: none
		sourceColumn: Customer Contact

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: 94a5c81a-1f7e-42eb-a497-a2ef9c5986a0
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Customer-8dc71ec3-8081-4cca-aa9c-f81949fbd6e1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\AnalyticsWithNaga\Videos\Projects\Video 2\Customer Ageing.xlsx"), null, true),
				    Customer_Sheet = Source{[Item="Customer",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Customer_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer name", type text}, {"Customer Contact", Int64.Type}, {"Address", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

